"""Add more user activity data columns

Revision ID: 5572c4904f9a
Revises: fa83fe3f3b1e
Create Date: 2024-09-24 22:55:30.610134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5572c4904f9a'
down_revision = 'fa83fe3f3b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('isAdmin', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('totalShifts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totalSwitchRequests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totalAcceptedSwitchRequests', sa.Integer(), nullable=True))

    # Remove server_default after updating all entries; this makes future insertions rely on model/ORM defaults
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('isAdmin', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totalAcceptedSwitchRequests')
        batch_op.drop_column('totalSwitchRequests')
        batch_op.drop_column('totalShifts')
        batch_op.drop_column('isAdmin')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
