"""Add password column to User table

Revision ID: fa83fe3f3b1e
Revises: 
Create Date: 2024-09-24 19:40:44.219322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa83fe3f3b1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('selectedShifts', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('currentShifts', sa.String(length=200), nullable=True))
        batch_op.drop_column('selectedshifts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selectedshifts', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('currentShifts')
        batch_op.drop_column('selectedShifts')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
